interfaces:
  project-upbit:
    url: https://project-team.upbit.com
  notification:
    telegram:
      url: https://api.telegram.org
    slack:
      url: https://hooks.slack.com/services
  api-upbit:
    url: https://api.upbit.com
  upbit-web:
    url: https://upbit.com
    exchange: ${interfaces.upbit-web.url}/exchange?code=CRIX.UPBIT.
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-test-query: select 1
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
feign:
  okhttp:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.56.201:3306/upbitbot?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      username: upbitbot
      password: 1234
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${database.host}:3306/upbitbot?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
